# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import signup.models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='1637819_640x640.jpg', upload_to=signup.models.upload_avatar_to),
        ),
    ]
