# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('coach_id', models.IntegerField()),
                ('p_interest', models.IntegerField(default=5)),
                ('c_interest', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='assistant_coach',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='coach',
            name='head_coach',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='coach',
            name='league',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='coach',
            name='username',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coach',
            name='video',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AddField(
            model_name='player',
            name='grad_year',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='video',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.CharField(default='none', max_length=25),
        ),
        migrations.AlterField(
            model_name='player',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
