# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20170420_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='first_name',
            field=models.CharField(default='Nico', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(default='Nico', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Nico', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Nico', max_length=25),
            preserve_default=False,
        ),
    ]
