# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0005_auto_20170428_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='c_interest',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='coach_id',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='p_interest',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='player_id',
        ),
        migrations.AddField(
            model_name='matches',
            name='interested',
            field=models.ManyToManyField(related_name='user_interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matches',
            name='interestee',
            field=models.ManyToManyField(related_name='user_interestee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='media/1051px-Harvard_Wreath_Logo_1.svg.png', max_length=100000, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(default='media/athletics-logo.jpg', max_length=100000, upload_to='media/'),
        ),
    ]
