# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20170429_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='video',
        ),
    ]
