# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20170429_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='Ali Smith', max_length=75),
        ),
    ]
