# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0010_auto_20170429_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='interested',
        ),
        migrations.AddField(
            model_name='matches',
            name='interested',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_interested', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='matches',
            name='interestee',
        ),
        migrations.AddField(
            model_name='matches',
            name='interestee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_interestee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
