# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20170429_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(default='coaches/duke-sports.jpg', max_length=100000, upload_to='coaches/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Midfield', 'Midfield'), ('Forward', 'Forward'), ('Defense', 'Defense')], max_length=25),
        ),
    ]
